# Generated by Django 5.0.3 on 2024-03-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_cart_totalamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantityToBuy',
            field=models.IntegerField(default=0),
        ),
    ]
