# Generated by Django 5.0.3 on 2024-03-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_cartitem_quantitytobuy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='purchaseDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
