# Generated by Django 5.0.3 on 2024-03-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_orderitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderAmount',
            field=models.FloatField(default=0),
        ),
    ]
